name: K6 Load Test

on:
  push:
    branches: [ "feat/swagger-tester" ]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 test
        run: |
          k6 run k6/team-load-test.js
        env:
          TOKEN: ${{ secrets.TOKEN }}A